version: '3.9'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '5432:5432'
    volumes:
      - postgres-data-graphql:/var/lib/postgresql/data
      - ./database/migrations:/docker-entrypoint-initdb.d/
    networks:
      - graphql-app

  app-graphql:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      GRAPHQL_PORT: 8080
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: todos
      DB_SSL_MODE: disable
    depends_on:
      - postgres
    ports:
      - '8080:8080'
    networks:
      - graphql-app
    restart: on-failure

volumes:
  postgres-data-graphql:

networks:
  graphql-app:
    driver: bridge
